create database kursach;
use kursach;
create table BaseProduct (BaseProduct_ID integer not null AUTO_INCREMENT, appearance integer,pr_name varchar(45), size integer, strength integer, thickness integer, weight integer, primary key (BaseProduct_ID));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Product (ProductID integer not null AUTO_INCREMENT, pr_name varchar(45), appearance integer, size integer, strength integer, thickness integer, weight integer, Series_SeriesID integer, BaseProducts_BaseProductID integer, Series_Workers_workerID integer, primary key (ProductID));
create table Seria (SeriaID integer not null AUTO_INCREMENT, date date, Users_UserID integer, Workers_workerID integer, primary key (SeriaID));
create table User (UserID integer not null AUTO_INCREMENT, login varchar(45) unique, password varchar(45), role integer, primary key (UserID));
create table Worker (WorkerID integer not null AUTO_INCREMENT, fio varchar(45),pr_name varchar(45), position varchar(45),otdel varchar(45), primary key (WorkerID));
alter table Product add constraint FKn96tqc0kk5m9tdfnem3r1xygq foreign key (Series_SeriesID) references Seria (SeriaID);
alter table Product add constraint FKj3btowylcqakk45bc42dvxkdn foreign key (BaseProducts_BaseProductID) references BaseProduct (BaseProduct_ID);
alter table Product add constraint FK45pewvoj4ntpmuecwovp0n3o foreign key (Series_Workers_workerID) references Worker (WorkerID);
alter table Seria add constraint FKgs12fwi9bvmuje95ejtorm8sc foreign key (Users_UserID) references User (UserID);
alter table Seria add constraint FK6s4h1q6n23m69v3dgrm65jt6v foreign key (Workers_workerID) references Worker (WorkerID);
INSERT INTO `baseproduct` VALUES (1,3,'ytrtr',4,5,6,4);
INSERT INTO `worker` VALUES (1,'Трус В.И.','test','Директор','Отдел'),(2,'test','test','test','Отдел'),(3,'test','test','test','Отдел');
INSERT INTO `user` VALUES (1,'Admin','1',0),(2,'User','user',1),(3,'test','123',0);
INSERT INTO `seria` VALUES (1,'2019-12-10',1,2);
INSERT INTO `product` VALUES (1,'TESST',6,5,6,9,5,1,1,1), (2,'TOL',4,4,4,4,3,1,1,3);