package Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    GRADE,

    ADD_PRODUCT,
    UPDATE_PRODUCT,
    GET_PRODUCT,
    DELETE_PRODUCT,
    GETALL_PRODUCT,

    ADD_USER,
    UPDATE_USER,
    GET_USER,
    DELETE_USER,
    GETALL_USER,

    ADD_WORKER,
    UPDATE_WORKER,
    GET_WORKER,
    DELETE_WORKER,
    GETALL_WORKER,

    ADD_BATCH,
    UPDATE_BATCH,
    GET_BATCH,
    DELETE_BATCH,
    GETALL_BATCH,

    ADD_STANDART,
    UPDATE_STANDART,
    GET_STANDART,
    DELETE_STANDART,
    GETALL_STANDART
}
